name: Hello Ansible

on: [push]

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Do Work
              run: echo "Hello Ansible"